Default: &defaults
  database: myFirstYesodSite.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: myFirstYesodSite_test.sqlite3
  <<: *defaults

Staging:
  database: myFirstYesodSite_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: myFirstYesodSite_production.sqlite3
  poolsize: 100
  <<: *defaults
